# Generated by Django 4.0 on 2022-01-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('point', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Buckets',
            fields=[
                ('bk_idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('wantDo', 'wantDo'), ('wantHave', 'wantHave')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='newlist.member')),
            ],
        ),
    ]
