# Generated by Django 4.0 on 2021-12-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buckets',
            fields=[
                ('bk_idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
